LITELLM_MASTER_KEY=sk-litellm-...replace-with-openssl-rand-hex-32...
LITELLM_SALT_KEY=...replace-with-another-openssl-rand-hex-32...
POSTGRES_PASSWORD=...replace-with-openssl-rand-hex-32...
ANTHROPIC_API_KEY=sk-ant-...
OPENAI_API_KEY=sk-...
OPENROUTER_API_KEY=sk-or-v1-...
DATABASE_URL=postgresql://litellm:${POSTGRES_PASSWORD}@db:5432/litellm
